"""Adding Email column to user table

Revision ID: 3a14c9b027b8
Revises: dc5c3fbe8b63
Create Date: 2020-11-01 12:14:22.542981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a14c9b027b8'
down_revision = 'dc5c3fbe8b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
